
# to install command line client:
# gem install travis --no-rdoc --no-ri

# to validate (note that r raises a misleading error):
# travis lint [path to your .travis.yml]

language: r

sudo: required

cache: packages

# https://docs.travis-ci.com/user/database-setup/#MongoDB
# MongoDB binds to 127.0.0.1 and requires no authentication
# or database creation up front
services:
  - mongodb

# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
# http://repo.mongodb.org/apt/ubuntu/dists/precise/mongodb-org/3.2/multiverse/binary-amd64/
addons:
  apt:
    packages:
    - mongodb-org
    - php5-cli
    sources:
    - mongodb-3.4-trusty


# to be added to use mongoimport for further travis testing:
#     - mongodb-org-tools
# as of 2016-04-10: travis build fails as follows:
# Disallowing packages: mongodb-org-tools
# If you require these packages, please review the package approval process at:
# https://github.com/travis-ci/apt-package-whitelist#package-approval-process
# comment to existing issue
# https://github.com/travis-ci/apt-package-whitelist/issues/2287
# new issue
# https://github.com/travis-ci/apt-package-whitelist/issues/2825

# https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html
r_github_packages:
  - jeroen/mongolite

r_packages:
  - covr
  - rvest

after_success:
  - Rscript -e 'library(covr); codecov()'

