
# to install command line client:
# gem install travis --no-rdoc --no-ri

# to validate:
# travis lint [path to your .travis.yml]

language: r

sudo: required

# https://docs.travis-ci.com/user/database-setup/#MongoDB
# MongoDB binds to 127.0.0.1 and requires no authentication
# or database creation up front
services:
  - mongodb

#apt_packages:
# - mongodb
